[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200
lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    lvgl/lvgl@8.4.0
build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_CONF_SUPPRESS_DEFINE_CHECK
    -std=gnu++17
    -Os
    -I src
board_build.arduino.memory_type = qio_opi